let busState=null;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function localInputNow(){const d=new Date(), off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16);}
function activeRoster(s){return (s.roster||[]).filter(r=>!r.archived&&String(r.status||'').toLowerCase()!=='archived').sort((a,b)=>{const ar=Number(a.roomNumber)||999,br=Number(b.roomNumber)||999;return ar-br||String(a.lastName||'').localeCompare(String(b.lastName||''));});}
function residentName(r){return (`${r.firstName||''} ${r.lastName||''}`).trim()||r.name||'Unnamed Resident';}
function renderResidents(){const sel=$('busResident');const current=sel.value;sel.innerHTML='<option value="">Select resident…</option>'+activeRoster(busState).map(r=>`<option value="${esc(r.id)}">${esc(residentName(r))}${r.roomNumber?` — Room ${esc(r.roomNumber)}`:''}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current;}
function fmt(iso){if(!iso)return'';const d=new Date(iso);return Number.isNaN(d.getTime())?iso:d.toLocaleString('en-CA',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function render(){const rows=[...(busState.busPassRecords||[])].sort((a,b)=>String(b.issuedAt).localeCompare(String(a.issuedAt)));$('busHistory').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(fmt(r.issuedAt))}</td><td><strong>${esc(r.residentName)}</strong></td><td>${esc(r.destination)}</td><td>${esc(r.passCount)}</td><td>${esc(r.tripType)}</td><td>${esc(r.staffName||r.staffEmail||'Staff')}</td><td>${esc(r.notes||'')}</td></tr>`).join(''):'<tr><td colspan="7" class="hint">No bus passes have been recorded yet.</td></tr>';const now=new Date(),today=now.toDateString(),weekAgo=now.getTime()-7*86400000;let td=0,wk=0,total=0;rows.forEach(r=>{const n=Number(r.passCount)||0,d=new Date(r.issuedAt);total+=n;if(!Number.isNaN(d.getTime())){if(d.toDateString()===today)td+=n;if(d.getTime()>=weekAgo)wk+=n;}});$('busToday').textContent=td;$('busWeek').textContent=wk;$('busTotal').textContent=total;renderResidents();}
async function init(){busState=await loadAppState();$('busIssuedAt').value=localInputNow();try{const i=await getCurrentStaffIdentity();$('busStaffBadge').textContent=i.name||'Signed in';}catch(_){}render();}
$('busPassForm').addEventListener('submit',async e=>{e.preventDefault();const resident=(busState.roster||[]).find(r=>r.id===$('busResident').value);if(!resident)return alert('Select a resident.');const identity=await getCurrentStaffIdentity();const local=$('busIssuedAt').value;const issuedAt=local?new Date(local).toISOString():new Date().toISOString();busState.busPassRecords=Array.isArray(busState.busPassRecords)?busState.busPassRecords:[];busState.busPassRecords.unshift({id:crypto.randomUUID(),residentId:resident.id,residentName:residentName(resident),issuedAt,destination:$('busDestination').value.trim(),passCount:Number($('busPassCount').value)||1,tripType:$('busTripType').value,staffName:identity.name,staffUid:identity.uid,staffEmail:identity.email,notes:$('busNotes').value.trim()});try{await saveAppState(busState);$('busDestination').value='';$('busPassCount').value='2';$('busTripType').value='Round Trip';$('busNotes').value='';$('busIssuedAt').value=localInputNow();render();if(window.kbrhToast)window.kbrhToast('Bus passes recorded.');}catch(err){console.error(err);alert('Could not save the bus pass record. No changes were intentionally removed.');}});
$('busPrint').addEventListener('click',()=>window.print());
init().catch(e=>{console.error(e);alert('Could not load the Bus Pass Tracker.');});
