let checkState=defaultAppState();let currentAreaId='';let currentRoom='';let editingCheckId='';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const today=()=>new Date().toISOString().slice(0,10);
function assignedName(areaId){const map={'washrooms':'Bathroom','upper-floors':'Upper floors','main-am':'Main Floor (morning)','main-pm':'Main Floor (Night)','basement':'Basement'},chore=map[areaId];if(!chore)return'';const idx=(checkState.chores||[]).indexOf(chore);const r=(checkState.residents||[]).find(x=>Number(x.choreIndex)===idx&&x.status!=='away');return r?.name||'';}
function latestRecord(areaId,room=''){return (checkState.choreChecks||[]).filter(x=>x.date===today()&&x.areaId===areaId&&String(x.roomNumber||'')===String(room||'')).sort((a,b)=>(b.updatedAt||b.createdAt||'').localeCompare(a.updatedAt||a.createdAt||''))[0];}
function statusFor(areaId){if(areaId==='rooms'){const done=RESIDENT_ROOM_NUMBERS.filter(n=>latestRecord('rooms',n)).length;return {label:`${done} / ${RESIDENT_ROOM_NUMBERS.length} rooms checked`,cls:done===RESIDENT_ROOM_NUMBERS.length?'complete':done?'partial':'pending'};}const rec=latestRecord(areaId);if(!rec)return{label:'Not checked',cls:'pending'};return rec.issuesFound?{label:'Checked — issues noted',cls:'issues'}:{label:'Complete',cls:'complete'};}
function renderGrid(){const grid=$('choreCheckGrid');grid.innerHTML=Object.entries(CHORE_CHECK_AREAS).map(([id,[name]])=>{const s=statusFor(id),assigned=id==='rooms'?'Room-by-room inspection':(assignedName(id)||'No resident currently assigned');return `<button class="tracker-card ${s.cls}" onclick="startArea('${id}')"><span class="tracker-card-title">${esc(name)}</span><span>${esc(assigned)}</span><strong>${esc(s.label)}</strong></button>`}).join('');$('checkDateLabel').textContent=new Date().toLocaleDateString('en-CA',{dateStyle:'long'});}
function startArea(id){if(id==='rooms')return openRoomPicker();openCheck(id,'');}function openRoomPicker(){$('roomButtonGrid').innerHTML=RESIDENT_ROOM_NUMBERS.map(n=>{const r=latestRecord('rooms',n);return `<button class="room-pick ${r?(r.issuesFound?'issues':'complete'):''}" onclick="openCheck('rooms','${n}')">Room ${n}<span>${r?(r.issuesFound?'Issues noted':'Checked'):'Not checked'}</span></button>`}).join('');$('roomPickerModal').classList.remove('hidden');document.body.classList.add('kbrh-modal-open');}
function closeRoomPicker(){$('roomPickerModal').classList.add('hidden');if($('checkModal').classList.contains('hidden'))document.body.classList.remove('kbrh-modal-open');}
function openCheck(areaId,room=''){currentAreaId=areaId;currentRoom=room;const [name,items]=CHORE_CHECK_AREAS[areaId],record=latestRecord(areaId,room);editingCheckId=record?.id||'';$('checkModalTitle').textContent=areaId==='rooms'?`Resident Room ${room}`:name;$('assignedResidentText').textContent=areaId==='rooms'?'Complete the inspection for this room.':`Assigned resident: ${assignedName(areaId)||'Not assigned'}`;$('checkItems').innerHTML=items.map((item,i)=>`<label class="checklist-row"><input type="checkbox" data-check-index="${i}" ${record?.completedItems?.includes(i)?'checked':''}><span>${esc(item)}</span></label>`).join('');$('checkDate').value=record?.date||today();$('checkedBy').value=record?.checkedBy||'';$('issuesFound').checked=Boolean(record?.issuesFound);$('checkNotes').value=record?.notes||'';closeRoomPicker();$('checkModal').classList.remove('hidden');document.body.classList.add('kbrh-modal-open');}
function closeCheck(){$('checkModal').classList.add('hidden');document.body.classList.remove('kbrh-modal-open');currentAreaId='';currentRoom='';editingCheckId='';}
async function saveCheck(){const checkedBy=$('checkedBy').value.trim();if(!checkedBy){alert('Enter the staff member who completed the check.');return;}const completedItems=[...document.querySelectorAll('[data-check-index]:checked')].map(x=>Number(x.dataset.checkIndex));const [name]=CHORE_CHECK_AREAS[currentAreaId];const rec={date:$('checkDate').value,areaId:currentAreaId,areaName:currentAreaId==='rooms'?`${name} — Room ${currentRoom}`:name,roomNumber:currentRoom,assignedResident:currentAreaId==='rooms'?'':assignedName(currentAreaId),checkedBy,completedItems,issuesFound:$('issuesFound').checked,notes:$('checkNotes').value.trim()};checkState.choreChecks=Array.isArray(checkState.choreChecks)?checkState.choreChecks:[];if(editingCheckId){Object.assign(checkState.choreChecks.find(x=>x.id===editingCheckId),rec,{updatedAt:new Date().toISOString()});}else checkState.choreChecks.unshift({...rec,id:crypto.randomUUID(),createdAt:new Date().toISOString()});await saveAppState(checkState);closeCheck();renderGrid();}
function openHistory(){const items=(checkState.choreChecks||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||'').localeCompare(a.createdAt||''));$('checkHistoryList').innerHTML=items.length?items.map(r=>`<article class="record-card"><div class="record-card-heading"><div><strong>${esc(r.areaName)}</strong><span>${esc(r.date)} · Checked by ${esc(r.checkedBy)}</span></div><span class="status-pill ${r.issuesFound?'status-danger':'status-success'}">${r.issuesFound?'Issues':'Complete'}</span></div>${r.assignedResident?`<p><strong>Assigned resident:</strong> ${esc(r.assignedResident)}</p>`:''}<p><strong>Completed:</strong> ${(r.completedItems||[]).length} / ${(CHORE_CHECK_AREAS[r.areaId]?.[1]||[]).length}</p>${r.notes?`<p><strong>Notes:</strong> ${esc(r.notes)}</p>`:''}</article>`).join(''):'<p class="empty-state">No chore checks have been saved.</p>';$('historyModal').classList.remove('hidden');document.body.classList.add('kbrh-modal-open');}
function closeHistory(){$('historyModal').classList.add('hidden');document.body.classList.remove('kbrh-modal-open');}
document.addEventListener('DOMContentLoaded',()=>{$('closeRoomPickerX').onclick=$('closeRoomPickerBtn').onclick=closeRoomPicker;$('closeCheckModalX').onclick=$('cancelCheckBtn').onclick=closeCheck;$('saveCheckBtn').onclick=saveCheck;$('viewCheckHistoryBtn').onclick=openHistory;$('closeHistoryX').onclick=$('closeHistoryBtn').onclick=closeHistory;});auth.onAuthStateChanged(u=>{if(!u)return;listenToAppState(s=>{checkState=s;renderGrid();});});