const PHASE2_LOG_USERS=new Set(["attendantj@kbrh.local","executivedirector@kbrh.local","admin@kbrh.local"]);let currentLogScope="phase1",logUnsub=null;
function phase2IdentityValues(){
  const u=auth.currentUser||{};
  const vals=[u.email,u.displayName];
  try{
    const keys=["email","username","userName","login","role","staffRole","accessLevel","name"];
    const sources=[window.currentUser,window.currentStaff,window.staffProfile,window.loggedInUser,window.userProfile];
    sources.forEach(o=>{if(o&&typeof o==="object")keys.forEach(k=>vals.push(o[k]))});
    ["currentUser","currentStaff","staffProfile","loggedInUser","userProfile","kbrhUser","kbrhStaff"].forEach(k=>{
      try{const o=JSON.parse(localStorage.getItem(k)||"null");if(o&&typeof o==="object")keys.forEach(x=>vals.push(o[x]))}catch(_){}
    });
  }catch(_){}
  return vals.filter(v=>v!=null).map(v=>String(v).trim().toLowerCase());
}
function canPhase2(){
  const vals=phase2IdentityValues();
  return vals.some(v=>PHASE2_LOG_USERS.has(v)||v==="admin"||v==="administrator"||v==="executive director"||v==="executivedirector");
}const LOGDOC=()=>db.collection("kbrh").doc(currentLogScope==="phase2"?"digitalLogbookPhase2":"digitalLogbook");let LS={entries:[]},AS={};const E=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function nm(r){return String(r?.name||[r?.firstName,r?.lastName].filter(Boolean).join(" ")||r?.residentName||"").trim()}
function residents(){
  const a=Array.isArray(AS?.roster)?AS.roster:[];
  const phase=currentLogScope==="phase2"?"phase2":"phase1";
  return a
    .filter(r=>r&&r!=="temp"&&!r.archived&&(r.phase||"phase1")===phase)
    .map(r=>({id:String(r.id||r.residentId||nm(r)),name:nm(r)}))
    .filter(r=>r.name)
    .sort((a,b)=>a.name.localeCompare(b.name));
}
function localNow(){let d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function oneSelect(){return `<select name="rid" required><option value="">Select resident…</option>${residents().map(r=>`<option value="${E(r.id)}">${E(r.name)}</option>`).join("")}</select>`}function multi(){return `<div class="lb-checks">${residents().map(r=>`<label class="lb-check"><input type="checkbox" name="rids" value="${E(r.id)}"> ${E(r.name)}</label>`).join("")||'<p class="hint">No active residents found.</p>'}</div>`}
function modal(title,body,save){let root=document.querySelector("#lbRoot");root.innerHTML=`<div class="lb-bg"><div class="lb-modal"><div class="lb-head"><h2>${E(title)}</h2><button type="button" id="lbx">×</button></div><form id="lbf"><div class="lb-body">${body}</div><div class="lb-foot"><button type="button" id="lbc">Cancel</button><button type="submit">Save Entry</button></div></form></div></div>`;let close=()=>root.innerHTML="";root.querySelector("#lbx").onclick=close;root.querySelector("#lbc").onclick=close;root.querySelector(".lb-bg").onclick=e=>{if(e.target===e.currentTarget)close()};root.querySelector("#lbf").onsubmit=async e=>{e.preventDefault();try{await save(new FormData(e.currentTarget));close()}catch(x){alert(x.message||"Unable to save.")}}}
async function staff(){return typeof getCurrentStaffIdentity==="function"?await getCurrentStaffIdentity():{uid:auth.currentUser?.uid||"",email:auth.currentUser?.email||"",name:typeof currentStaffName==="function"?currentStaffName():"Staff User"}}
async function updateEntry(id,patch){let st=await staff(),q=await LOGDOC().get(),d=q.exists?q.data():{},a=Array.isArray(d.entries)?d.entries:[],i=a.findIndex(e=>e.id===id);if(i<0)throw Error("Log entry was not found.");a[i]={...a[i],...patch,lastEditedAt:new Date().toISOString(),lastEditedBy:st.name||"Unknown Staff",lastEditedByUid:st.uid||""};await LOGDOC().set({entries:a,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
async function add(x){let s=await staff(),e={logScope:currentLogScope,id:`log-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,...x,enteredBy:s.name||"Unknown Staff",enteredByUid:s.uid||"",enteredByEmail:s.email||"",createdAt:new Date().toISOString()},q=await LOGDOC().get(),d=q.exists?q.data():{},a=Array.isArray(d.entries)?d.entries:[];await LOGDOC().set({entries:[...a,e],updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
function movement(){modal("Resident In / Out",`<div class="lb-field"><label>Time</label><input type="datetime-local" name="time" value="${localNow()}" required></div><div class="lb-field"><label>Resident</label>${oneSelect()}</div><div class="lb-field"><label>In / Out</label><select name="dir" required><option value="">Select…</option><option value="OUT">Out — Resident Left</option><option value="IN">In — Resident Returned</option></select></div>`,async f=>{let r=residents().find(x=>x.id===f.get("rid"));if(!r)throw Error("Select a resident.");let dir=f.get("dir"),t=f.get("time");await add({type:"movement",residentId:r.id,residentName:r.name,direction:dir,eventTime:new Date(t).toISOString(),summary:`${r.name} — ${dir==="OUT"?"LEFT":"RETURNED"}`})})}
function meds(){modal("Medication Delivery",`<div class="lb-field"><label>Pharmacy</label><select name="pharmacy" required><option value="">Select…</option><option>Medicine Shoppe</option><option>Pharmaright</option></select></div><div class="lb-field"><label>Resident(s)</label>${multi()}</div><div class="lb-field"><label>What was delivered?</label><textarea name="delivered" rows="5" required placeholder="Type what was delivered…"></textarea></div>`,async f=>{let ids=f.getAll("rids");if(!ids.length)throw Error("Select at least one resident.");let rs=residents().filter(r=>ids.includes(r.id)),d=String(f.get("delivered")||"").trim();if(!d)throw Error("Enter what was delivered.");await add({type:"medication",pharmacy:f.get("pharmacy"),residentIds:rs.map(r=>r.id),residentNames:rs.map(r=>r.name),delivered:d,summary:`Medication Delivery — ${f.get("pharmacy")}`})})}
function note(){modal("Log Book Note",`<div class="lb-field"><label>Note</label><textarea name="note" rows="7" required placeholder="Enter details…"></textarea></div>`,async f=>{let n=String(f.get("note")||"").trim();if(!n)throw Error("Enter a note.");await add({type:"note",note:n,summary:"Staff Note"})})}
function dt(v){let d=new Date(v);return !v||isNaN(d)?"—":d.toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}
function toLocalInput(v){let d=new Date(v);if(isNaN(d))return localNow();let p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function render(){let b=document.querySelector("#logEntries"),a=[...(LS.entries||[])].sort((x,y)=>String(y.createdAt||"").localeCompare(String(x.createdAt||"")));b.innerHTML=a.length?a.slice(0,250).map(e=>{let d=e.type==="movement"?`<strong>${E(e.residentName)}</strong> ${e.direction==="OUT"?"left":"returned"} at ${dt(e.eventTime)}.`:e.type==="medication"?`<strong>${E(e.pharmacy)}</strong> — ${E((e.residentNames||[]).join(", "))}<br>${E(e.delivered)}`:E(e.note||"");let edited=e.lastEditedAt?`<div class="lb-edit-note">Edited by ${E(e.lastEditedBy||"Unknown Staff")} • ${dt(e.lastEditedAt)}</div>`:"";return `<article class="lb-entry"><div class="lb-entry-head"><div><h3>${E(e.summary||"Log Entry")}</h3></div><div class="lb-entry-actions"><button type="button" data-edit-log="${E(e.id)}">Edit</button></div></div><div>${d}</div><div class="lb-meta">Entered by ${E(e.enteredBy||"Unknown Staff")} • ${dt(e.createdAt)}</div>${edited}</article>`}).join(""):'<p class="hint">No log entries yet.</p>';b.querySelectorAll("[data-edit-log]").forEach(x=>x.onclick=()=>editEntry(x.dataset.editLog))}
function editEntry(id){let e=(LS.entries||[]).find(x=>x.id===id);if(!e)return alert("Log entry not found.");if(e.type==="movement"){let opts=residents().map(r=>`<option value="${E(r.id)}" ${String(r.id)===String(e.residentId)?"selected":""}>${E(r.name)}</option>`).join("");modal("Edit Resident In / Out",`<div class="lb-field"><label>Time</label><input type="datetime-local" name="time" value="${toLocalInput(e.eventTime)}" required></div><div class="lb-field"><label>Resident</label><select name="rid" required>${opts}</select></div><div class="lb-field"><label>In / Out</label><select name="dir" required><option value="OUT" ${e.direction==="OUT"?"selected":""}>Out — Resident Left</option><option value="IN" ${e.direction==="IN"?"selected":""}>In — Resident Returned</option></select></div>`,async f=>{let r=residents().find(x=>x.id===f.get("rid"));if(!r)throw Error("Select a resident.");let dir=f.get("dir");await updateEntry(id,{residentId:r.id,residentName:r.name,direction:dir,eventTime:new Date(f.get("time")).toISOString(),summary:`${r.name} — ${dir==="OUT"?"LEFT":"RETURNED"}`})})}else if(e.type==="medication"){let checks=residents().map(r=>`<label class="lb-check"><input type="checkbox" name="rids" value="${E(r.id)}" ${(e.residentIds||[]).map(String).includes(String(r.id))?"checked":""}> ${E(r.name)}</label>`).join("");modal("Edit Medication Delivery",`<div class="lb-field"><label>Pharmacy</label><select name="pharmacy" required><option ${e.pharmacy==="Medicine Shoppe"?"selected":""}>Medicine Shoppe</option><option ${e.pharmacy==="Pharmaright"?"selected":""}>Pharmaright</option></select></div><div class="lb-field"><label>Resident(s)</label><div class="lb-checks">${checks}</div></div><div class="lb-field"><label>What was delivered?</label><textarea name="delivered" rows="5" required>${E(e.delivered||"")}</textarea></div>`,async f=>{let ids=f.getAll("rids");if(!ids.length)throw Error("Select at least one resident.");let rs=residents().filter(r=>ids.includes(r.id)),d=String(f.get("delivered")||"").trim();await updateEntry(id,{pharmacy:f.get("pharmacy"),residentIds:rs.map(r=>r.id),residentNames:rs.map(r=>r.name),delivered:d,summary:`Medication Delivery — ${f.get("pharmacy")}`})})}else{modal("Edit Log Book Note",`<div class="lb-field"><label>Note</label><textarea name="note" rows="7" required>${E(e.note||"")}</textarea></div>`,async f=>{let n=String(f.get("note")||"").trim();if(!n)throw Error("Enter a note.");await updateEntry(id,{note:n})})}}
function entryDate(e){let v=e.type==="movement"&&e.eventTime?e.eventTime:e.createdAt,d=new Date(v);if(isNaN(d))return "";let p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function printReport(){let day=document.querySelector("#reportDate").value;if(!day)return alert("Select a report date.");let a=[...(LS.entries||[])].filter(e=>entryDate(e)===day).sort((x,y)=>String((x.eventTime||x.createdAt)||"").localeCompare(String((y.eventTime||y.createdAt)||"")));let title=new Date(day+"T12:00:00").toLocaleDateString([],{weekday:"long",year:"numeric",month:"long",day:"numeric"});let rows=a.map(e=>{let detail=e.type==="movement"?`${E(e.residentName)} — ${e.direction==="OUT"?"LEFT":"RETURNED"} at ${dt(e.eventTime)}`:e.type==="medication"?`${E(e.pharmacy)} — ${E((e.residentNames||[]).join(", "))}: ${E(e.delivered)}`:E(e.note||"");return `<tr><td>${dt(e.eventTime||e.createdAt)}</td><td>${E(e.summary||"Log Entry")}</td><td>${detail}</td><td>${E(e.enteredBy||"Unknown Staff")}</td></tr>`}).join("");let w=window.open("","_blank","width=1000,height=800");w.document.write(`<!doctype html><html><head><title>Log Book Report - ${E(title)}</title><style>body{font-family:Arial,sans-serif;margin:28px;color:#111}h1{margin-bottom:4px}p{margin-top:0}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #999;padding:8px;text-align:left;vertical-align:top}th{background:#eee}@media print{body{margin:12mm}}</style></head><body><h1>Ken Brown Recovery Home</h1><p><strong>${currentLogScope==="phase2"?"Phase 2":"Phase 1"} Digital Log Book — ${E(title)}</strong></p>${a.length?`<table><thead><tr><th>Time</th><th>Entry</th><th>Details</th><th>Entered By</th></tr></thead><tbody>${rows}</tbody></table>`:"<p>No log book entries for this date.</p>"}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
async function subscribeLog(){if(logUnsub)logUnsub();LS={entries:[]};render();logUnsub=LOGDOC().onSnapshot(s=>{LS=s.exists?s.data():{entries:[]};render()},e=>console.error(e))}
async function start(){let sel=document.querySelector("#logbookScope");if(canPhase2()){sel.insertAdjacentHTML("beforeend",'<option value="phase2">Phase 2 Log</option>')}else{document.querySelector("#logbookSelectorCard").style.display="none"}sel.value="phase1";sel.onchange=async()=>{let requested=sel.value;if(requested==="phase2"&&!canPhase2()){sel.value="phase1";return alert("You do not have access to the Phase 2 log book.")}currentLogScope=requested;await subscribeLog()};document.querySelector("#reportDate").value=new Date().toISOString().slice(0,10);document.querySelector("#printReportBtn").onclick=printReport;document.querySelectorAll("[data-reason]").forEach(b=>b.onclick=()=>({movement,medication:meds,note}[b.dataset.reason])());try{if(typeof loadAppState==="function")AS=await loadAppState()||{};if(typeof APP_DOC_REF==="function")APP_DOC_REF().onSnapshot(s=>{if(s.exists)AS=s.data()||{}})}catch(e){console.warn(e)}await subscribeLog()}
auth.onAuthStateChanged(u=>{if(u)start()});