const LOGDOC=()=>db.collection("kbrh").doc("digitalLogbook");let LS={entries:[]},AS={};const E=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function nm(r){return String(r?.name||[r?.firstName,r?.lastName].filter(Boolean).join(" ")||r?.residentName||"").trim()}function residents(){let a=Array.isArray(AS?.roster)?AS.roster:Array.isArray(AS?.residents)?AS.residents:[];return a.filter(r=>!r?.discharged&&!r?.inactive&&String(r?.status||"").toLowerCase()!=="discharged").map(r=>({id:String(r.id||r.residentId||nm(r)),name:nm(r)})).filter(r=>r.name).sort((a,b)=>a.name.localeCompare(b.name))}
function localNow(){let d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function oneSelect(){return `<select name="rid" required><option value="">Select resident…</option>${residents().map(r=>`<option value="${E(r.id)}">${E(r.name)}</option>`).join("")}</select>`}function multi(){return `<div class="lb-checks">${residents().map(r=>`<label class="lb-check"><input type="checkbox" name="rids" value="${E(r.id)}"> ${E(r.name)}</label>`).join("")||'<p class="hint">No active residents found.</p>'}</div>`}
function modal(title,body,save){let root=document.querySelector("#lbRoot");root.innerHTML=`<div class="lb-bg"><div class="lb-modal"><div class="lb-head"><h2>${E(title)}</h2><button type="button" id="lbx">×</button></div><form id="lbf"><div class="lb-body">${body}</div><div class="lb-foot"><button type="button" id="lbc">Cancel</button><button type="submit">Save Entry</button></div></form></div></div>`;let close=()=>root.innerHTML="";root.querySelector("#lbx").onclick=close;root.querySelector("#lbc").onclick=close;root.querySelector(".lb-bg").onclick=e=>{if(e.target===e.currentTarget)close()};root.querySelector("#lbf").onsubmit=async e=>{e.preventDefault();try{await save(new FormData(e.currentTarget));close()}catch(x){alert(x.message||"Unable to save.")}}}
async function staff(){return typeof getCurrentStaffIdentity==="function"?await getCurrentStaffIdentity():{uid:auth.currentUser?.uid||"",email:auth.currentUser?.email||"",name:typeof currentStaffName==="function"?currentStaffName():"Staff User"}}
async function add(x){let s=await staff(),e={id:`log-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,...x,enteredBy:s.name||"Unknown Staff",enteredByUid:s.uid||"",enteredByEmail:s.email||"",createdAt:new Date().toISOString()},q=await LOGDOC().get(),d=q.exists?q.data():{},a=Array.isArray(d.entries)?d.entries:[];await LOGDOC().set({entries:[...a,e],updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
function movement(){modal("Resident In / Out",`<div class="lb-field"><label>Time</label><input type="datetime-local" name="time" value="${localNow()}" required></div><div class="lb-field"><label>Resident</label>${oneSelect()}</div><div class="lb-field"><label>In / Out</label><select name="dir" required><option value="">Select…</option><option value="OUT">Out — Resident Left</option><option value="IN">In — Resident Returned</option></select></div>`,async f=>{let r=residents().find(x=>x.id===f.get("rid"));if(!r)throw Error("Select a resident.");let dir=f.get("dir"),t=f.get("time");await add({type:"movement",residentId:r.id,residentName:r.name,direction:dir,eventTime:new Date(t).toISOString(),summary:`${r.name} — ${dir==="OUT"?"LEFT":"RETURNED"}`})})}
function meds(){modal("Medication Delivery",`<div class="lb-field"><label>Pharmacy</label><select name="pharmacy" required><option value="">Select…</option><option>Medicine Shoppe</option><option>Pharmaright</option></select></div><div class="lb-field"><label>Resident(s)</label>${multi()}</div><div class="lb-field"><label>What was delivered?</label><textarea name="delivered" rows="5" required placeholder="Type what was delivered…"></textarea></div>`,async f=>{let ids=f.getAll("rids");if(!ids.length)throw Error("Select at least one resident.");let rs=residents().filter(r=>ids.includes(r.id)),d=String(f.get("delivered")||"").trim();if(!d)throw Error("Enter what was delivered.");await add({type:"medication",pharmacy:f.get("pharmacy"),residentIds:rs.map(r=>r.id),residentNames:rs.map(r=>r.name),delivered:d,summary:`Medication Delivery — ${f.get("pharmacy")}`})})}
function note(){modal("Log Book Note",`<div class="lb-field"><label>Note</label><textarea name="note" rows="7" required placeholder="Enter details…"></textarea></div>`,async f=>{let n=String(f.get("note")||"").trim();if(!n)throw Error("Enter a note.");await add({type:"note",note:n,summary:"Staff Note"})})}
function dt(v){let d=new Date(v);return !v||isNaN(d)?"—":d.toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}function render(){let b=document.querySelector("#logEntries"),a=[...(LS.entries||[])].sort((x,y)=>String(y.createdAt||"").localeCompare(String(x.createdAt||"")));b.innerHTML=a.length?a.slice(0,250).map(e=>{let d=e.type==="movement"?`<strong>${E(e.residentName)}</strong> ${e.direction==="OUT"?"left":"returned"} at ${dt(e.eventTime)}.`:e.type==="medication"?`<strong>${E(e.pharmacy)}</strong> — ${E((e.residentNames||[]).join(", "))}<br>${E(e.delivered)}`:E(e.note||"");return `<article class="lb-entry"><h3>${E(e.summary||"Log Entry")}</h3><div>${d}</div><div class="lb-meta">Entered by ${E(e.enteredBy||"Unknown Staff")} • ${dt(e.createdAt)}</div></article>`}).join(""):'<p class="hint">No log entries yet.</p>'}
async function start(){document.querySelectorAll("[data-reason]").forEach(b=>b.onclick=()=>({movement,medication:meds,note}[b.dataset.reason])());try{if(typeof loadAppState==="function")AS=await loadAppState()||{};if(typeof APP_DOC_REF==="function")APP_DOC_REF().onSnapshot(s=>{if(s.exists)AS=s.data()||{}})}catch(e){console.warn(e)}LOGDOC().onSnapshot(s=>{LS=s.exists?s.data():{entries:[]};render()},e=>console.error(e))}
auth.onAuthStateChanged(u=>{if(u)start()});