const INCIDENT_TYPES=["Aggressive Behaviour","Self-Harm/Suicidal Ideation","Medical Emergency","Fall/Injury","Suspected Substance Use","Property Damage","AWOL/Unauthorized Absence","Other"];
const IMMEDIATE_ACTIONS=["First Aid Provided","Emergency Services Called (EMS/Police)","Client Moved to Safe Location","Supervisor Notified","Parent/Guardian/Case Worker Notified","Other"];
let incidentState=defaultAppState();let editingIncidentId="";
const ir=id=>document.getElementById(id);
const irEsc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function activeRoster(){return (incidentState.roster||[]).filter(r=>r&&!r.archived&&(r.phase||"phase1")!=="archived");}
function getResident(id){return (incidentState.roster||[]).find(r=>r.id===id);}
function fullName(r){return `${r?.firstName||""} ${r?.lastName||""}`.trim();}
function today(){return new Date().toISOString().slice(0,10);}
function choiceHtml(prefix,values,selected=[]){return values.map((v,i)=>`<label class="incident-choice"><input type="checkbox" name="${prefix}" value="${irEsc(v)}" ${selected.includes(v)?"checked":""}><span>${irEsc(v)}</span></label>`).join("");}
function fillResidentSelect(selected=""){ir("irResident").innerHTML='<option value="">Select resident...</option>'+activeRoster().sort((a,b)=>fullName(a).localeCompare(fullName(b))).map(r=>`<option value="${r.id}" ${r.id===selected?"selected":""}>${irEsc(fullName(r))}${r.roomNumber?` — Room ${irEsc(r.roomNumber)}`:""}</option>`).join("");syncResidentFields();}
function syncResidentFields(){const r=getResident(ir("irResident").value);ir("irDob").value=r?.dob||"";ir("irRoom").value=r?.roomNumber||"";ir("irAdmissionDate").value=r?.entryDate||"";}
function selectedValues(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);}
function addWitness(name="",contact=""){const row=document.createElement("div");row.className="incident-form-grid witness-row";row.style.marginBottom="8px";row.innerHTML=`<div class="incident-field"><label>Witness Name</label><input class="witness-name" value="${irEsc(name)}"></div><div class="incident-field"><label>Contact Info</label><div style="display:flex;gap:7px"><input class="witness-contact" value="${irEsc(contact)}"><button class="secondary remove-witness" type="button" aria-label="Remove witness">×</button></div></div>`;row.querySelector('.remove-witness').onclick=()=>row.remove();ir("witnessRows").appendChild(row);}
function witnesses(){return [...document.querySelectorAll('.witness-row')].map(row=>({name:row.querySelector('.witness-name').value.trim(),contact:row.querySelector('.witness-contact').value.trim()})).filter(x=>x.name||x.contact);}
function toggleOtherFields(){ir("otherIncidentTypeWrap").classList.toggle("hidden",!selectedValues("incidentType").includes("Other"));ir("otherActionWrap").classList.toggle("hidden",!selectedValues("immediateAction").includes("Other"));}
function openIncidentModal(report=null){editingIncidentId=report?.id||"";ir("incidentForm").querySelectorAll("input,select,textarea").forEach(x=>x.disabled=false);ir("incidentForm").querySelector('button[type="submit"]').style.display="";ir("incidentModalTitle").textContent=report?"Edit Resident Incident Report":"New Resident Incident Report";ir("incidentTypeChoices").innerHTML=choiceHtml("incidentType",INCIDENT_TYPES,report?.incidentTypes||[]);ir("immediateActionChoices").innerHTML=choiceHtml("immediateAction",IMMEDIATE_ACTIONS,report?.immediateActions||[]);fillResidentSelect(report?.residentId||"");ir("irDate").value=report?.incidentDate||today();ir("irTime").value=report?.incidentTime||"";ir("irLocation").value=report?.incidentLocation||"";ir("irOtherType").value=report?.otherIncidentType||"";ir("irDescription").value=report?.description||"";ir("irOtherAction").value=report?.otherImmediateAction||"";ir("irImmediateDescription").value=report?.immediateActionDescription||"";ir("irClientInjured").value=report?.clientInjured||"No";ir("irClientInjury").value=report?.clientInjuryDescription||"";ir("irOthersInjured").value=report?.othersInjured||"No";ir("irOthersInjury").value=report?.othersInjuryDescription||"";ir("witnessRows").innerHTML="";(report?.witnesses||[]).forEach(w=>addWitness(w.name,w.contact));ir("irStaffName").value=report?.staffName||(typeof currentStaffName==="function"?currentStaffName():(auth.currentUser?.displayName||auth.currentUser?.email||""));ir("irStaffName").readOnly=!report;if(!report&&!ir("irStaffPosition").value&&typeof currentStaffPosition==="function")ir("irStaffPosition").value=currentStaffPosition();ir("irStaffPosition").value=report?.staffPosition||"";ir("irStaffSignature").value=report?.staffSignature||"";ir("irReportDate").value=report?.reportDate||today();ir("irEdName").value=report?.executiveDirectorName||"";ir("irReviewedDate").value=report?.dateReviewed||"";ir("irFollowUpRequired").value=report?.followUpRequired||"No";ir("irEdFollowUp").value=report?.executiveFollowUp||"";ir("irEdSignature").value=report?.executiveDirectorSignature||"";ir("irFollowUpDetails").value=report?.followUpDetails||"";toggleOtherFields();ir("incidentModal").classList.remove("hidden");document.body.classList.add("kbrh-modal-open");}
function closeIncidentModal(){ir("incidentModal").classList.add("hidden");document.body.classList.remove("kbrh-modal-open");editingIncidentId="";}
function reportFromForm(){const r=getResident(ir("irResident").value);return {id:editingIncidentId||crypto.randomUUID(),residentId:r?.id||"",residentName:fullName(r),clientDob:r?.dob||"",roomNumber:r?.roomNumber||"",admissionDate:r?.entryDate||"",incidentDate:ir("irDate").value,incidentTime:ir("irTime").value,incidentLocation:ir("irLocation").value.trim(),incidentTypes:selectedValues("incidentType"),otherIncidentType:ir("irOtherType").value.trim(),description:ir("irDescription").value.trim(),immediateActions:selectedValues("immediateAction"),otherImmediateAction:ir("irOtherAction").value.trim(),immediateActionDescription:ir("irImmediateDescription").value.trim(),clientInjured:ir("irClientInjured").value,clientInjuryDescription:ir("irClientInjury").value.trim(),othersInjured:ir("irOthersInjured").value,othersInjuryDescription:ir("irOthersInjury").value.trim(),witnesses:witnesses(),staffName:ir("irStaffName").value.trim(),staffPosition:ir("irStaffPosition").value.trim(),staffSignature:ir("irStaffSignature").value.trim(),reportDate:ir("irReportDate").value,executiveDirectorName:ir("irEdName").value.trim(),dateReviewed:ir("irReviewedDate").value,followUpRequired:ir("irFollowUpRequired").value,executiveFollowUp:ir("irEdFollowUp").value.trim(),executiveDirectorSignature:ir("irEdSignature").value.trim(),followUpDetails:ir("irFollowUpDetails").value.trim(),status:ir("irReviewedDate").value?"Reviewed":"Submitted",createdAt:editingIncidentId?(incidentState.incidentReports.find(x=>x.id===editingIncidentId)?.createdAt||new Date().toISOString()):new Date().toISOString(),updatedAt:new Date().toISOString()};}
async function saveIncident(e){e.preventDefault();const report=reportFromForm();if(!report.residentId||!report.incidentDate||!report.incidentTime||!report.incidentLocation||!report.description||!report.staffName||!report.staffPosition){alert("Please complete the required fields.");return;}if(report.incidentTypes.length===0){alert("Select at least one incident type.");return;}const idx=(incidentState.incidentReports||[]).findIndex(x=>x.id===report.id);if(idx>=0)incidentState.incidentReports[idx]=report;else incidentState.incidentReports.unshift(report);await saveAppState(incidentState);closeIncidentModal();renderIncidentReports();}
function formatDate(v){if(!v)return"";const d=new Date(v+"T00:00:00");return Number.isNaN(d)?v:d.toLocaleDateString("en-CA",{year:"numeric",month:"short",day:"numeric"});}
function renderIncidentReports(){const reports=[...(incidentState.incidentReports||[])].sort((a,b)=>`${b.incidentDate}${b.incidentTime}`.localeCompare(`${a.incidentDate}${a.incidentTime}`));ir("incidentTotalCount").textContent=reports.length;const ym=new Date().toISOString().slice(0,7);ir("incidentMonthCount").textContent=reports.filter(x=>(x.incidentDate||"").startsWith(ym)).length;ir("incidentFollowUpCount").textContent=reports.filter(x=>x.followUpRequired==="Yes"||x.followUpDetails).length;ir("incidentReportBody").innerHTML=reports.length?reports.map(r=>`<tr><td><strong>${irEsc(r.residentName||"Unknown Resident")}</strong>${r.roomNumber?`<div class="hint">Room ${irEsc(r.roomNumber)}</div>`:""}</td><td>${irEsc(formatDate(r.incidentDate))}<div class="hint">${irEsc(r.incidentTime||"")}</div></td><td>${irEsc((r.incidentTypes||[]).join(", ")||"—")}</td><td>${irEsc(r.incidentLocation||"—")}</td><td><span class="status-badge ${r.status==="Reviewed"?"status-success":"status-info"}">${irEsc(r.status||"Submitted")}</span></td><td><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="secondary" type="button" onclick="viewIncident('${r.id}')">View</button><button type="button" onclick="editIncident('${r.id}')">Edit</button><button class="secondary" type="button" onclick="printIncident('${r.id}')">Print</button></div></td></tr>`).join(""):`<tr><td colspan="6" style="text-align:center;padding:32px;color:#64748b">No incident reports have been recorded.</td></tr>`;}
window.editIncident=id=>{const r=(incidentState.incidentReports||[]).find(x=>x.id===id);if(r)openIncidentModal(r);};
window.viewIncident=id=>{const r=(incidentState.incidentReports||[]).find(x=>x.id===id);if(!r)return;const old=ir("incidentForm").querySelectorAll("input,select,textarea,button");openIncidentModal(r);setTimeout(()=>{ir("incidentModalTitle").textContent="Resident Incident Report";ir("incidentForm").querySelectorAll("input,select,textarea").forEach(x=>x.disabled=true);ir("incidentForm").querySelector('button[type="submit"]').style.display="none";},0);};
window.printIncident=id=>{const r=(incidentState.incidentReports||[]).find(x=>x.id===id);if(!r)return;const win=window.open("","_blank");const rows=(label,val)=>`<tr><th>${irEsc(label)}</th><td>${irEsc(val||"—")}</td></tr>`;win.document.write(`<!doctype html><html><head><title>Incident Report - ${irEsc(r.residentName)}</title><style>body{font-family:Arial;margin:32px;color:#111}h1{margin-bottom:2px}small{font-weight:bold}.conf{color:#900}.section{margin-top:20px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aaa;padding:8px;text-align:left;vertical-align:top}th{width:30%;background:#eee}@media print{button{display:none}}</style></head><body><h1>Ken Brown Recovery Home</h1><small>Client Incident Report Form — <span class="conf">CONFIDENTIAL</span></small><div class="section"><table>${rows("Resident",r.residentName)}${rows("DOB",r.clientDob)}${rows("Room / Unit",r.roomNumber)}${rows("Admission Date",formatDate(r.admissionDate))}${rows("Incident Date",formatDate(r.incidentDate))}${rows("Incident Time",r.incidentTime)}${rows("Location",r.incidentLocation)}${rows("Incident Type",(r.incidentTypes||[]).join(", "))}${rows("Description",r.description)}${rows("Immediate Actions",(r.immediateActions||[]).join(", "))}${rows("Action Details",r.immediateActionDescription)}${rows("Client Injured",r.clientInjured)}${rows("Client Injury",r.clientInjuryDescription)}${rows("Others Injured",r.othersInjured)}${rows("Other Injury Details",r.othersInjuryDescription)}${rows("Staff",`${r.staffName||""} — ${r.staffPosition||""}`)}${rows("Executive Director",r.executiveDirectorName)}${rows("Follow-Up Required",r.followUpRequired)}${rows("Follow-Up",[r.executiveFollowUp,r.followUpDetails].filter(Boolean).join(" | "))}</table></div><p style="margin-top:22px"><button onclick="window.print()">Print</button></p></body></html>`);win.document.close();};
ir("newIncidentBtn").onclick=()=>openIncidentModal();ir("closeIncidentModalBtn").onclick=closeIncidentModal;ir("cancelIncidentBtn").onclick=closeIncidentModal;ir("incidentForm").onsubmit=saveIncident;ir("irResident").onchange=syncResidentFields;ir("addWitnessBtn").onclick=()=>addWitness();ir("incidentTypeChoices").addEventListener("change",toggleOtherFields);ir("immediateActionChoices").addEventListener("change",toggleOtherFields);ir("incidentModal").addEventListener("mousedown",e=>{if(e.target===ir("incidentModal"))closeIncidentModal();});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!ir("incidentModal").classList.contains("hidden"))closeIncidentModal();});
auth.onAuthStateChanged(user=>{if(!user)return;listenToAppState(next=>{incidentState=next;renderIncidentReports();});});
