let reportState=defaultAppState();
const OUTCOMES={completed:"Program Completed",involuntary:"Involuntary Discharge / Removed","voluntary-goals":"Voluntary Departure — Felt They Got Enough From Program","voluntary-other":"Voluntary Withdrawal / Left Early",medical:"Medical / Health",transfer:"Transfer to Another Service",legal:"Incarcerated / Legal",other:"Other"};
function dateOnly(v){return String(v||"").slice(0,10)}
function within(v){const d=dateOnly(v),a=document.getElementById("reportStart").value,b=document.getElementById("reportEnd").value;if(!d)return false;return(!a||d>=a)&&(!b||d<=b)}
function isReturned(r){return r.dischargeOutcomeCode==="returned-waitlist"||String(r.archiveReason||"").toLowerCase().includes("moved back to waitlist")}
function codeFor(r){if(r.dischargeOutcomeCode)return r.dischargeOutcomeCode;const x=String(r.archiveReason||"").toLowerCase();if(x.includes("complete"))return"completed";if(x.includes("involuntary")||x.includes("removed"))return"involuntary";if(isReturned(r))return"returned-waitlist";return r.archived?"legacy-other":""}
function monthKey(v){const d=dateOnly(v);return d?d.slice(0,7):""}
function monthLabel(k){if(!k)return"";const [y,m]=k.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString("en-CA",{year:"numeric",month:"long"})}
function metrics(){const roster=(reportState.roster||[]).filter(Boolean);const intakeRows=roster.filter(r=>r.entryDate&&within(r.entryDate)&&!isReturned(r));const discharged=roster.filter(r=>r.archived&&r.archivedAt&&within(r.archivedAt)&&!isReturned(r));const counts={};discharged.forEach(r=>{const c=codeFor(r)||"legacy-other";counts[c]=(counts[c]||0)+1});const completed=counts.completed||0,removed=counts.involuntary||0,den=completed+removed;return{roster,intakes:intakeRows.length,discharged,counts,completed,removed,rate:den?completed/den*100:null}}
function render(){const m=metrics();kpiIntakes.textContent=m.intakes;kpiCompleted.textContent=m.completed;kpiRemoved.textContent=m.removed;kpiSuccess.textContent=m.rate==null?"—":m.rate.toFixed(1)+"%";const order=["completed","involuntary","voluntary-goals","voluntary-other","medical","transfer","legal","other","legacy-other"];outcomeBody.innerHTML=order.map(c=>{const n=m.counts[c]||0;if(!n&&c==="legacy-other")return"";const label=c==="legacy-other"?"Legacy / Unclassified":OUTCOMES[c];return`<tr><td>${label}</td><td>${n}</td><td>${c==="completed"||c==="involuntary"?"Yes":"No"}</td></tr>`}).join("");const months={};m.roster.forEach(r=>{if(r.entryDate&&within(r.entryDate)&&!isReturned(r)){const k=monthKey(r.entryDate);months[k]??={i:0,c:0,r:0,o:0};months[k].i++}if(r.archived&&r.archivedAt&&within(r.archivedAt)&&!isReturned(r)){const k=monthKey(r.archivedAt);months[k]??={i:0,c:0,r:0,o:0};const c=codeFor(r);if(c==="completed")months[k].c++;else if(c==="involuntary")months[k].r++;else months[k].o++}});monthlyBody.innerHTML=Object.keys(months).sort().reverse().map(k=>{const x=months[k],d=x.c+x.r,rate=d?(x.c/d*100).toFixed(1)+"%":"—";return`<tr><td>${monthLabel(k)}</td><td>${x.i}</td><td>${x.c}</td><td>${x.r}</td><td>${x.o}</td><td>${rate}</td></tr>`}).join("")||'<tr><td colspan="6" class="hint">No reportable records in this date range.</td></tr>'}
function exportCsv(){const m=metrics();const rows=[["Metric","Value"],["Intakes",m.intakes],["Program Completed",m.completed],["Involuntary / Removed",m.removed],["Success Rate",m.rate==null?"":m.rate.toFixed(1)+"%"],["",""],["Outcome","Count"]];Object.entries(m.counts).forEach(([c,n])=>rows.push([OUTCOMES[c]||"Legacy / Unclassified",n]));const csv=rows.map(r=>r.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="KBRH-Outcome-Report.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
applyReport.onclick=render;resetReport.onclick=()=>{reportStart.value="";reportEnd.value="";render()};exportReport.onclick=exportCsv;listenToAppState(s=>{reportState=normalizeAppState(s);render()});