let toolState=null; const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function localNow(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16);}
function fmt(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-CA',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function name(r){return (`${r.firstName||''} ${r.lastName||''}`).trim()||r.name||'Unnamed Resident';}
function activeRoster(){return (toolState.roster||[]).filter(r=>!r.archived&&String(r.status||'').toLowerCase()!=='archived').sort((a,b)=>(Number(a.roomNumber)||999)-(Number(b.roomNumber)||999)||name(a).localeCompare(name(b)));}
function renderResidents(){const s=$('toolResident'),v=s.value;s.innerHTML='<option value="">Select resident…</option>'+activeRoster().map(r=>`<option value="${esc(r.id)}">${esc(name(r))}${r.roomNumber?` — Room ${esc(r.roomNumber)}`:''}</option>`).join('');if([...s.options].some(o=>o.value===v))s.value=v;}
function rows(){return [...(toolState.toolSignOutRecords||[])].sort((a,b)=>String(b.timeOut).localeCompare(String(a.timeOut)));}
function render(){renderResidents();const all=rows(),out=all.filter(r=>!r.timeIn);$('toolOutCount').textContent=`${out.length} out`;$('toolOutBody').innerHTML=out.length?out.map(r=>`<tr><td><strong>${esc(r.residentName)}</strong></td><td>${esc(r.reason)}</td><td>${esc(fmt(r.timeOut))}</td><td>${esc(r.tool)}</td><td>${esc(r.toolId)}</td><td>${esc(r.issuedByName||r.issuedByEmail||'Staff')}</td><td><button type="button" class="tool-return-btn" data-return="${esc(r.id)}">Mark Returned</button></td></tr>`).join(''):'<tr><td colspan="7" class="hint">No tools are currently signed out.</td></tr>';$('toolHistoryBody').innerHTML=all.length?all.map(r=>`<tr><td>${esc(r.residentName)}</td><td>${esc(r.reason)}</td><td>${esc(fmt(r.timeOut))}</td><td>${esc(fmt(r.timeIn))}</td><td>${esc(r.tool)}</td><td>${esc(r.toolId)}</td></tr>`).join(''):'<tr><td colspan="6" class="hint">No tool sign-outs recorded yet.</td></tr>';document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>markReturned(b.dataset.return));}
async function markReturned(id){const rec=(toolState.toolSignOutRecords||[]).find(r=>r.id===id);if(!rec||rec.timeIn)return;const identity=await getCurrentStaffIdentity();rec.timeIn=new Date().toISOString();rec.returnedByName=identity.name;rec.returnedByUid=identity.uid;rec.returnedByEmail=identity.email;rec.updatedAt=new Date().toISOString();try{await saveAppState(toolState);render();window.kbrhToast?.('Tool marked returned.');}catch(e){console.error(e);rec.timeIn='';alert('Could not mark the tool returned. No return was recorded.');}}
$('toolForm').addEventListener('submit',async e=>{e.preventDefault();const resident=(toolState.roster||[]).find(r=>r.id===$('toolResident').value);if(!resident)return alert('Select a resident.');const identity=await getCurrentStaffIdentity();const local=$('toolTimeOut').value;const timeOut=local?new Date(local).toISOString():new Date().toISOString();toolState.toolSignOutRecords=Array.isArray(toolState.toolSignOutRecords)?toolState.toolSignOutRecords:[];toolState.toolSignOutRecords.unshift({id:crypto.randomUUID(),residentId:resident.id,residentName:name(resident),reason:$('toolReason').value.trim(),timeOut,timeIn:'',tool:$('toolName').value.trim(),toolId:$('toolId').value.trim(),issuedByName:identity.name,issuedByUid:identity.uid,issuedByEmail:identity.email,returnedByName:'',returnedByUid:'',returnedByEmail:'',updatedAt:new Date().toISOString()});try{await saveAppState(toolState);$('toolReason').value='';$('toolName').value='';$('toolId').value='';$('toolTimeOut').value=localNow();render();window.kbrhToast?.('Tool signed out.');}catch(err){console.error(err);alert('Could not save the tool sign-out. No record was intentionally removed.');}});
$('toolPrint').onclick=()=>window.print();
(async()=>{toolState=await loadAppState();$('toolTimeOut').value=localNow();try{const i=await getCurrentStaffIdentity();$('toolStaffBadge').textContent=i.name||'Signed in';}catch(_){}render();})().catch(e=>{console.error(e);alert('Could not load Tool Sign-Out.');});
