let toolState=null;
let pendingInventoryToolId='';
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function localNow(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16);}
function fmt(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-CA',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function residentName(r){return (`${r.firstName||''} ${r.lastName||''}`).trim()||r.name||'Unnamed Resident';}
function activeRoster(){return (toolState.roster||[]).filter(r=>!r.archived&&String(r.status||'').toLowerCase()!=='archived').sort((a,b)=>(Number(a.roomNumber)||999)-(Number(b.roomNumber)||999)||residentName(a).localeCompare(residentName(b)));}
function inventory(){toolState.toolInventory=Array.isArray(toolState.toolInventory)?toolState.toolInventory:[];return toolState.toolInventory;}
function records(){toolState.toolSignOutRecords=Array.isArray(toolState.toolSignOutRecords)?toolState.toolSignOutRecords:[];return [...toolState.toolSignOutRecords].sort((a,b)=>String(b.timeOut).localeCompare(String(a.timeOut)));}
function currentRecordForTool(tool){return records().find(r=>!r.timeIn && ((r.inventoryToolId&&r.inventoryToolId===tool.id)||(!r.inventoryToolId&&String(r.toolId||'').trim().toLowerCase()===String(tool.toolId||'').trim().toLowerCase())));}
function renderResidents(){const s=$('toolResident'),v=s.value;s.innerHTML='<option value="">Select resident…</option>'+activeRoster().map(r=>`<option value="${esc(r.id)}">${esc(residentName(r))}${r.roomNumber?` — Room ${esc(r.roomNumber)}`:''}</option>`).join('');if([...s.options].some(o=>o.value===v))s.value=v;}
function statusChip(out){return out?'<span class="tool-status tool-status-out">OUT</span>':'<span class="tool-status tool-status-available">AVAILABLE</span>';}
function renderInventory(){const list=[...inventory()].sort((a,b)=>String(a.tool||'').localeCompare(String(b.tool||''))||String(a.toolId||'').localeCompare(String(b.toolId||'')));const outCount=list.filter(t=>currentRecordForTool(t)).length;$('inventoryTotal').textContent=list.length;$('inventoryOut').textContent=outCount;$('inventoryAvailable').textContent=list.length-outCount;$('toolInventoryBody').innerHTML=list.length?list.map(t=>{const out=currentRecordForTool(t);return `<tr><td><strong>${esc(t.tool)}</strong></td><td>${esc(t.toolId)}</td><td>${statusChip(!!out)}</td><td>${out?esc(out.residentName):'<span class="hint">—</span>'}</td><td>${out?`<button type="button" class="secondary tool-return-btn" data-return="${esc(out.id)}">Mark Returned</button>`:`<button type="button" data-signout="${esc(t.id)}">Sign Out</button>`}</td></tr>`;}).join(''):'<tr><td colspan="5" class="hint">No tools in inventory yet. Use + Add Tool to begin.</td></tr>';}
function render(){renderResidents();renderInventory();const all=records(),out=all.filter(r=>!r.timeIn);$('toolOutCount').textContent=`${out.length} out`;$('toolOutBody').innerHTML=out.length?out.map(r=>`<tr><td><strong>${esc(r.residentName)}</strong></td><td>${esc(r.reason)}</td><td>${esc(fmt(r.timeOut))}</td><td>${esc(r.tool)}</td><td>${esc(r.toolId)}</td><td>${esc(r.issuedByName||r.issuedByEmail||'Staff')}</td><td><button type="button" class="tool-return-btn" data-return="${esc(r.id)}">Mark Returned</button></td></tr>`).join(''):'<tr><td colspan="7" class="hint">No tools are currently signed out.</td></tr>';$('toolHistoryBody').innerHTML=all.length?all.map(r=>`<tr><td>${esc(r.residentName)}</td><td>${esc(r.reason)}</td><td>${esc(fmt(r.timeOut))}</td><td>${esc(fmt(r.timeIn))}</td><td>${esc(r.tool)}</td><td>${esc(r.toolId)}</td></tr>`).join(''):'<tr><td colspan="6" class="hint">No tool sign-outs recorded yet.</td></tr>';document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>markReturned(b.dataset.return));document.querySelectorAll('[data-signout]').forEach(b=>b.onclick=()=>openSignOutModal(b.dataset.signout));}
function openAddToolModal(){$('inventoryToolName').value='';$('inventoryToolId').value='';$('addToolModal').classList.remove('hidden');setTimeout(()=>$('inventoryToolName').focus(),0);}
function closeAddToolModal(){$('addToolModal').classList.add('hidden');}
function openSignOutModal(id){const tool=inventory().find(t=>t.id===id);if(!tool)return;if(currentRecordForTool(tool))return alert('This tool is already signed out.');pendingInventoryToolId=id;$('signOutToolTitle').textContent='Sign Out Tool';$('signOutToolSummary').textContent=`${tool.tool} — ID # ${tool.toolId}`;$('toolResident').value='';$('toolReason').value='';$('toolTimeOut').value=localNow();$('signOutToolModal').classList.remove('hidden');}
function closeSignOutModal(){pendingInventoryToolId='';$('signOutToolModal').classList.add('hidden');}
async function markReturned(id){const rec=(toolState.toolSignOutRecords||[]).find(r=>r.id===id);if(!rec||rec.timeIn)return;const old={timeIn:rec.timeIn,returnedByName:rec.returnedByName,returnedByUid:rec.returnedByUid,returnedByEmail:rec.returnedByEmail,updatedAt:rec.updatedAt};const identity=await getCurrentStaffIdentity();rec.timeIn=new Date().toISOString();rec.returnedByName=identity.name;rec.returnedByUid=identity.uid;rec.returnedByEmail=identity.email;rec.updatedAt=new Date().toISOString();try{await saveAppState(toolState);render();window.kbrhToast?.('Tool marked returned.');}catch(e){console.error(e);Object.assign(rec,old);render();alert('Could not mark the tool returned. No return was recorded.');}}
$('addToolForm').addEventListener('submit',async e=>{e.preventDefault();const tool=$('inventoryToolName').value.trim(),toolId=$('inventoryToolId').value.trim();if(!tool||!toolId)return;const duplicate=inventory().find(t=>String(t.toolId||'').trim().toLowerCase()===toolId.toLowerCase());if(duplicate)return alert(`ID # ${toolId} is already assigned to ${duplicate.tool}.`);const identity=await getCurrentStaffIdentity();const rec={id:crypto.randomUUID(),tool,toolId,createdAt:new Date().toISOString(),createdByName:identity.name,createdByUid:identity.uid,createdByEmail:identity.email,updatedAt:new Date().toISOString()};toolState.toolInventory.push(rec);try{await saveAppState(toolState);closeAddToolModal();render();window.kbrhToast?.('Tool added to inventory.');}catch(err){console.error(err);toolState.toolInventory=toolState.toolInventory.filter(t=>t.id!==rec.id);render();alert('Could not add the tool to inventory.');}});
$('signOutToolForm').addEventListener('submit',async e=>{e.preventDefault();const tool=inventory().find(t=>t.id===pendingInventoryToolId);const resident=(toolState.roster||[]).find(r=>r.id===$('toolResident').value);if(!tool)return alert('Tool not found. Close this window and try again.');if(currentRecordForTool(tool))return alert('This tool is already signed out.');if(!resident)return alert('Select a resident.');const reason=$('toolReason').value.trim();if(!reason)return alert('Enter a reason.');const identity=await getCurrentStaffIdentity();const local=$('toolTimeOut').value;const timeOut=local?new Date(local).toISOString():new Date().toISOString();const rec={id:crypto.randomUUID(),inventoryToolId:tool.id,residentId:resident.id,residentName:residentName(resident),reason,timeOut,timeIn:'',tool:tool.tool,toolId:tool.toolId,issuedByName:identity.name,issuedByUid:identity.uid,issuedByEmail:identity.email,returnedByName:'',returnedByUid:'',returnedByEmail:'',updatedAt:new Date().toISOString()};toolState.toolSignOutRecords.unshift(rec);try{await saveAppState(toolState);closeSignOutModal();render();window.kbrhToast?.('Tool signed out.');}catch(err){console.error(err);toolState.toolSignOutRecords=toolState.toolSignOutRecords.filter(r=>r.id!==rec.id);render();alert('Could not save the tool sign-out. No sign-out was recorded.');}});
$('addToolBtn').onclick=openAddToolModal;document.querySelectorAll('[data-close-add]').forEach(b=>b.onclick=closeAddToolModal);document.querySelectorAll('[data-close-signout]').forEach(b=>b.onclick=closeSignOutModal);
// Close tool dialogs when the shaded overlay itself is clicked, and with Escape.
['addToolModal','signOutToolModal'].forEach(id=>{
  const modal=$(id);
  modal?.addEventListener('click',e=>{
    if(e.target!==modal)return;
    if(id==='addToolModal')closeAddToolModal();else closeSignOutModal();
  });
});
document.addEventListener('keydown',e=>{
  if(e.key!=='Escape')return;
  if(!$('signOutToolModal')?.classList.contains('hidden'))closeSignOutModal();
  else if(!$('addToolModal')?.classList.contains('hidden'))closeAddToolModal();
});

$('toolPrint').onclick=()=>window.print();
(async()=>{toolState=await loadAppState();toolState.toolInventory=Array.isArray(toolState.toolInventory)?toolState.toolInventory:[];toolState.toolSignOutRecords=Array.isArray(toolState.toolSignOutRecords)?toolState.toolSignOutRecords:[];try{const i=await getCurrentStaffIdentity();$('toolStaffBadge').textContent=i.name||'Signed in';}catch(_){}render();})().catch(e=>{console.error(e);alert('Could not load Tool Sign-Out.');});
