let writeupState=defaultAppState();let selectedResidentId='';let editingWriteupId=null;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function activeRoster(){return (writeupState.roster||[]).filter(r=>r&&r!=='temp'&&!r.archived&&['phase1','phase2'].includes(r.phase||'phase1')).sort((a,b)=>`${a.lastName} ${a.firstName}`.localeCompare(`${b.lastName} ${b.firstName}`));}
function residentName(r){return `${r.firstName||''} ${r.lastName||''}`.trim();}function recordsFor(id){return (writeupState.writeUps||[]).filter(w=>w.residentId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));}
function renderRoster(){const b=$('writeupRosterBody');const rows=activeRoster();b.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(residentName(r))}</td><td><strong>${recordsFor(r.id).length}</strong></td><td><button class="secondary" onclick="openWriteupDetails('${r.id}')">More Info</button></td></tr>`).join(''):'<tr><td colspan="3" class="empty">No active residents found.</td></tr>';}
function openWriteupDetails(id){selectedResidentId=id;const r=activeRoster().find(x=>x.id===id)||(writeupState.roster||[]).find(x=>x.id===id);if(!r)return;$('writeupModalTitle').textContent=`Write-Ups — ${residentName(r)}`;$('writeupModalHint').textContent=`${recordsFor(id).length} write-up${recordsFor(id).length===1?'':'s'} recorded.`;renderHistory();$('writeupModal').classList.remove('hidden');document.body.classList.add('kbrh-modal-open');}
function renderHistory(){const list=$('writeupHistory'),items=recordsFor(selectedResidentId);list.innerHTML=items.length?items.map(w=>`<article class="record-card"><div class="record-card-heading"><div><strong>${esc(w.date||'Date not entered')}</strong><span>Given by ${esc(w.issuedBy||'Not recorded')}</span></div><div class="actions"><button class="secondary" onclick="openWriteupForm('${w.id}')">Edit</button><button class="danger" onclick="deleteWriteup('${w.id}')">Delete</button></div></div><p><strong>Reason:</strong> ${esc(w.reason)}</p>${w.notes?`<p><strong>Notes:</strong> ${esc(w.notes)}</p>`:''}</article>`).join(''):'<p class="empty-state">No write-ups recorded for this resident.</p>';}
function closeDetails(){$('writeupModal').classList.add('hidden');document.body.classList.remove('kbrh-modal-open');selectedResidentId='';}
function openWriteupForm(id=''){editingWriteupId=id;const w=(writeupState.writeUps||[]).find(x=>x.id===id);$('writeupFormTitle').textContent=w?'Edit Write-Up':'Add Write-Up';$('saveWriteupBtn').textContent=w?'Save Changes':'Save Write-Up';$('writeupDate').value=w?.date||new Date().toISOString().slice(0,10);$('writeupIssuedBy').value=w?.issuedBy||'';$('writeupReason').value=w?.reason||'';$('writeupNotes').value=w?.notes||'';$('writeupFormModal').classList.remove('hidden');}
function closeForm(){$('writeupFormModal').classList.add('hidden');editingWriteupId=null;}
async function saveWriteup(){const r=(writeupState.roster||[]).find(x=>x.id===selectedResidentId);if(!r)return;const rec={residentId:r.id,residentName:residentName(r),date:$('writeupDate').value,issuedBy:$('writeupIssuedBy').value.trim(),reason:$('writeupReason').value.trim(),notes:$('writeupNotes').value.trim()};if(!rec.date||!rec.issuedBy||!rec.reason){alert('Date, reason, and staff member are required.');return;}writeupState.writeUps=Array.isArray(writeupState.writeUps)?writeupState.writeUps:[];if(editingWriteupId){Object.assign(writeupState.writeUps.find(x=>x.id===editingWriteupId),rec,{updatedAt:new Date().toISOString()});}else writeupState.writeUps.unshift({...rec,id:crypto.randomUUID(),createdAt:new Date().toISOString()});await saveAppState(writeupState);closeForm();renderHistory();renderRoster();}
async function deleteWriteup(id){if(!confirm('Delete this write-up record?'))return;writeupState.writeUps=(writeupState.writeUps||[]).filter(x=>x.id!==id);await saveAppState(writeupState);renderHistory();renderRoster();}
document.addEventListener('DOMContentLoaded',()=>{$('addWriteupBtn').onclick=()=>openWriteupForm();$('closeWriteupModalBtn').onclick=$('closeWriteupModalX').onclick=closeDetails;$('closeWriteupFormX').onclick=$('cancelWriteupBtn').onclick=closeForm;$('saveWriteupBtn').onclick=saveWriteup;});auth.onAuthStateChanged(u=>{if(!u)return;listenToAppState(s=>{writeupState=s;renderRoster();if(selectedResidentId)renderHistory();});});